# Configurações do Site.
title: Analista de Suporte / Analista de Segurança da Informação em Barueri/SP
description: "Um blog sobre coisas novas que estou aprendendo ou interessado, e para fixar tudo que estou praticando."
author: Andrey Glauzer
email: nglauzer@gmail.com
nome: Andrey
background: cover.jpg
AuthorImagem: blog-author.jpg
ImagemSocial: social.png
keyword: pfSense, Linux, SonicWall, Fortinet, Python, DigitalOcean, Wordpress, FreeBSD, Magento, Debian, Ubuntu, OpenSUSE, Zabbix, Raspberry, Acronis, Bitdefender, Switchs Cisco, ESXI, Hyper-V, Macafee, Symantec Backup, Veeam Backup, HTML5, CSS3, JavaScript, PHP, Apache, Windows Server, Git, GitHub, Docker, Photoshop, Amazon Webservices

# Configurações da Build
baseurl: "/"
markdown: kramdown
source: .
destination: ./_site

# Configuração de paginação
pagination:
  enabled: true
  per_page: 1000
  permalink: '/page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Blogs
collections:
    posts:
        output: true
        permalink: /blog/:title/

# Convigurações Padrões
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins que eu utilizo
gems:
  - jekyll-paginate-v2
  - jemoji

# Redes sociais
whatsapp: 11950597632
linkedin: andreyglauzer
github: andreyglauzer
twitter: nglauzer

# Configurações de Skills
# Deser ser um icone em SVG, porque o layout está configurado para esse formato
skills:
  - name: pfSense
    icon: pfsense.svg

  - name: Linux
    icon: linux.svg

  - name: SonicWall
    icon: sonicwall.svg

  - name: Fortinet
    icon: fortinet.svg

  - name: Python
    icon: python.svg

  - name: DigitalOcean
    icon: digitalocean.svg

  - name: Wordpress
    icon: wordpress.svg

  - name: FreeBSD
    icon: freebsd.svg

  - name: Magento
    icon: magento.svg

  - name: Debian
    icon: Debian.svg

  - name: Ubuntu
    icon: Ubuntu.svg

  - name: OpenSUSE
    icon: OpenSUSE.svg

  - name: Zabbix
    icon: Zabbix.svg

  - name: Raspberry
    icon: Raspberry.svg

  - name: Acronis
    icon: Acronis.svg

  - name: Bitdefender
    icon: Bitdefender.svg

  - name: Switchs Cisco
    icon: Cisco.svg

  - name: ESXI
    icon: ESXI.svg

  - name: Hyper-V
    icon: Hyper-V.svg

  - name: Macafee
    icon: Macafee.svg

  - name: Symantec Backup
    icon: Symantec.svg

  - name: Veeam Backup
    icon: HP.svg

  - name: HTML5
    icon: html5.svg

  - name: CSS3
    icon: css3.svg

  - name: JavaScript
    icon: javascript.svg

  - name: PHP
    icon: php.svg

  - name: Apache
    icon: apache.svg

  - name: Windows Server
    icon: windows.svg

  - name: Git
    icon: git.svg

  - name: GitHub
    icon: github.svg

  - name: Docker
    icon: docker.svg

  - name: Photoshop
    icon: photoshop.svg

  - name: Amazon Webservices
    icon: amazonwebservices.svg


# Configurações de projetos
projeto:
  - name: Corre Cajamar
    imagem: correcajamar.png
    description: Projeto escrito em Django, feito para o grupo de atletas do cajamar, com painel administrativo e hospedado na kinghost.
    url: https://correcajamar.com.br
    site: https://correcajamar.com.br
    date: Março de 2018
    default: true
    invert: false

  - name: pybook
    imagem: pybook.png
    description: Projeto escrito em Python, que coleta o maximo de informações de outros sites, com base nos livros mais lidos do site Skoob, coletando como link para download do arquivo, descrição Livro/Autor, menor preço etc..
    url: https://github.com/andreyglauzer/pybook
    site: https://andreyglauzer.com/pybook
    date: Setembro de 2017
    invert: true

  - name: andreyglauzer.com
    imagem: andreyglauzer.png
    description: Meu blog pessoal, desenvolvido com GitHub Pages, com a ajuda o Jekyll <3.
    url: https://github.com/andreyglauzer/andreyglauzer.github.io
    site: https://andreyglauzer.com/
    date: Janeiro de 2016
    invert: false

  - name: Cortexiphan
    imagem: cortexiphan.png
    description: Projeto desenvolvido em Python, que faz coleta no youtube, juntando informações de canais e playlists de cursos focados na área de T.I
    url: https://github.com/andreyglauzer/cortexiphan
    site: https://andreyglauzer.com/cortexiphan
    date: Agosto de 2017
    invert: true
    
  - name: Alidoces Oficial
    imagem: alidocesoficial.png
    description: Projeto desenvolvido para um amigo, para o mesmo poder divulgar o trabalho que sua esposa faz de venda de bolos no pote, e bolos sobre encomendas.
    url: https://github.com/andreyglauzer/alidocesoficial.github.io
    site: https://alidocesoficial.com
    date: Janeiro de 2017
    invert: false

